
GET http://localhost:4000/customers

GET http://localhost:4000/customers/2023

GET http://localhost:4000/customers/page/2

POST http://localhost:4000/customers
Content-Type: application/json

{
    "email": "newUse1r@gmail.com",
    "first_name": "new",
    "last_name": "user",
    "ip": "255.255.255.255",
    "latitude": 27.634171,
    "longitude": 52.273891
}

PUT http://localhost:4000/customers
Content-Type: application/json

{
    "id": 2023,
    "email": "newUser3@gmail.com",
    "first_name": "new",
    "last_name": "user",
    "ip": "255.255.255.255",
    "latitude": 27.634171,
    "longitude": 52.273891
}

DELETE http://localhost:4000/customers/1

POST http://localhost:4000/customers/search
Content-Type: application/json

{
    "ip": "255.255.255.255",
    "email": "newUser3@gmail.com"
}

POST http://localhost:4000/customers/searchWithType
Content-Type: application/json

{
    "search_type": "first_name",
    "first_name": "Sa"
}
